# Every field must be added to the root build.gradle expandProps map.

# Common
java_version = 21
mod_version = 0.3.3
group = it.crystalnest
mod_authors = Crystal Spider
mod_title = Fancy Entity Renderer
mod_id = fancy_entity_renderer
mod_id_kebab = fancy-entity-renderer
license = CNCLv1
description = I'm a fancy GUI!
credits = Keksuccino, Travonoski, Achim von Lowtzow
github_user = crystal-nest
curseforge_id = 1173643
minecraft_version = 1.21.4
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft = 1.21.4
parchment_version = 2025.03.23
# https://projects.neoforged.net/neoforged/neoform
neo_form_version = 1.21.4-20241203.161809

# Fabric (https://fabricmc.net/develop/)
fabric_version = 0.114.0+1.21.4
fabric_loader_version = 0.16.9

# NeoForge (https://projects.neoforged.net/neoforged/neoforge)
neoforge_version = 21.4.121
neoforge_loader_version_range = [21.4,)

# Dependencies
mixin_extras_version = 0.4.1
soul_fire_d_version = 5.1.6

# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
