# Every field must be added to the root build.gradle expandProps map.

# Common
java_version = 25
mod_version = 0.5.4
group = it.crystalnest
mod_authors = Crystal Spider
mod_title = Fancy Entity Renderer
mod_id = fancy_entity_renderer
mod_id_kebab = fancy-entity-renderer
license = CNCLv1
description = I'm a fancy GUI!
credits = Keksuccino
github_user = crystal-nest
curseforge_id = 1173643
minecraft_version = 26.1.1
# https://minecraft.wiki/w/Pack_format#List_of_data_pack_formats
pack_format = 94.1
# https://projects.neoforged.net/neoforged/neoform
neo_form_version = 26.1.1-1

# Fabric (https://fabricmc.net/develop/)
fabric_version = 0.145.3+26.1.1
fabric_loader_version = 0.18.6
fabric_loom_version = 1.15.5

# NeoForge (https://projects.neoforged.net/neoforged/neoforge)
neoforge_version = 26.1.1.6-beta
neoforge_loader_version_range = [26.1,)

# Dependencies
mixin_extras_version = 0.4.1
prometheus_version = 1.2.5
prometheus_minecraft_version = 26.1
cobweb_version = 1.4.0
cobweb_minecraft_version = 26.1

# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
