plugins {
  id "multiloader-common"
  id "fabric-loom"
}

dependencies {
  minecraft "com.mojang:minecraft:$minecraft_version"
  mappings loom.layered {
    officialMojangMappings()
    parchment("org.parchmentmc.data:parchment-$parchment_minecraft:$parchment_version@zip")
  }
  compileOnly "org.spongepowered:mixin:0.8.5"
  compileOnly "net.fabricmc:fabric-loader:$fabric_loader_version"
  compileOnly "io.github.llamalad7:mixinextras-common:$mixin_extras_version"
  annotationProcessor "io.github.llamalad7:mixinextras-common:$mixin_extras_version"
  compileOnly("it.crystalnest:soul-fire-d-$name:$minecraft_version-$soul_fire_d_version")
}

loom {
  def aw = file("src/main/resources/${mod_id}.accesswidener")
  if (aw.exists()) {
    accessWidenerPath.set(aw)
  }
  mixin {
    defaultRefmapName.set("${mod_id}.refmap.json")
  }
}

configurations {
  commonJava {
    canBeResolved = false
    canBeConsumed = true
  }
  commonResources {
    canBeResolved = false
    canBeConsumed = true
  }
}

artifacts {
  commonJava sourceSets.main.java.sourceDirectories.singleFile
  commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

// Disable publishing tasks where common is not published
tasks.named("publishModrinth").get().setEnabled(false)
tasks.named("publishCurseforge").get().setEnabled(false)
tasks.named("publishGitHub").get().setEnabled(false)
